/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import url from "../objects/Box.glb"

export default function Model({isEnd}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(url)
  const { actions } = useAnimations(animations, group)

useEffect(() => {
  console.log(actions.Animation)
  if (isEnd) {
    actions.Animation.play()
    setTimeout(() => {actions.Animation.paused = true}, 22000)
  }
}, [isEnd])

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Placeholder-Cube_Green">
          <group name="Cube_cell013_cell001_37" position={[0.78, 1.28, 0.71]}>
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell002_38" position={[0.34, 1.68, -0.74]}>
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell003_39" position={[0.13, 1.7, -0.16]}>
            <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell004_40" position={[0.8, 1.7, -0.52]}>
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell005_41" position={[0.41, 1.17, -0.77]}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell006_42" position={[0.05, 1.32, -0.73]}>
            <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell007_43" position={[0.14, 1.14, -0.17]}>
            <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell008_44" position={[0.49, 1.31, -0.35]}>
            <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell009_45" position={[0.01, 1.25, -0.34]}>
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell010_46" position={[0.86, 0.61, -0.17]}>
            <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell011_47" position={[0.1, 0.77, -0.39]}>
            <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell012_48" position={[0.27, 0.22, -0.2]}>
            <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell013_49" position={[0.33, 0.38, -0.73]}>
            <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell014_50" position={[0.54, 0.79, -0.26]}>
            <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell015_51" position={[0.65, 0.57, -0.77]}>
            <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell016_52" position={[0.61, 0.03, -0.3]}>
            <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell017_53" position={[0.9, 1.22, 0.2]}>
            <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell018_54" position={[0.22, 1.79, 0.49]}>
            <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell019_55" position={[0.26, 1.33, 0.77]}>
            <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell020_56" position={[0.55, 1.27, 0.28]}>
            <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell021_57" position={[0.17, 1.24, 0.3]}>
            <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell022_58" position={[0.79, 1.67, 0.26]}>
            <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell023_0" position={[0.65, 1.71, 0.74]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell024_59" position={[0.53, 0.67, 0.25]}>
            <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell025_60" position={[0.76, 0.24, 0.57]}>
            <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell026_61" position={[0.38, 0.24, 0.25]}>
            <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell027_62" position={[0.73, 0.73, 0.68]}>
            <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell028_63" position={[0.32, 0.33, 0.74]}>
            <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell029_64" position={[0.22, 0.71, 0.69]}>
            <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell030_65" position={[0.88, 0.44, 0.16]}>
            <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell031_66" position={[0.17, 0.78, 0.15]}>
            <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell032_67" position={[-0.3, 1.74, -0.38]}>
            <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell033_68" position={[-0.3, 1.74, -0.72]}>
            <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell034_69" position={[-0.31, 1.32, -0.71]}>
            <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell035_70" position={[-0.76, 1.4, -0.31]}>
            <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell036_71" position={[-0.3, 1.22, -0.32]}>
            <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell037_72" position={[-0.29, 0.2, 0.42]}>
            <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell038_73" position={[-0.08, 0.09, 0.47]}>
            <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell039_3" position={[-0.01, 0.23, 0.81]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell040_74" position={[-0.08, 0.27, 0.56]}>
            <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell041_75" position={[-0.16, 0.26, 0.05]}>
            <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell042_76" position={[-0.38, 0.12, 0.05]}>
            <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell043_4" position={[-0.3, 0.01, 0.11]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell044_77" position={[-0.26, 0.31, 0.25]}>
            <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell045_78" position={[-0.73, 0.91, 0.3]}>
            <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell046_79" position={[-0.85, 0.65, 0.24]}>
            <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell047_80" position={[-0.58, 0.55, 0.31]}>
            <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell048_81" position={[-0.88, 0.65, 0.59]}>
            <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell049_82" position={[-0.57, 0.49, 0.49]}>
            <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell050_5" position={[-0.49, 0.99, 0.28]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell051_83" position={[-0.61, 0.84, 0.51]}>
            <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell052_84" position={[-0.45, 0.63, 0.77]}>
            <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell053_85" position={[-0.13, 0.63, 0.61]}>
            <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell054_86" position={[-0.05, 0.75, 0.18]}>
            <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell055_6" position={[-0.02, 0.92, -0.03]}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell056_87" position={[-0.22, 0.93, 0.22]}>
            <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell057_88" position={[-0.03, 0.96, 0.22]}>
            <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell058_89" position={[-0.25, 0.66, 0.34]}>
            <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell059_90" position={[-0.12, 0.87, 0.66]}>
            <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell060_91" position={[-0.69, 0.66, 0.1]}>
            <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell061_92" position={[-0.83, 0.88, -0.02]}>
            <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell062_93" position={[-0.66, 0.63, -0.04]}>
            <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell063_94" position={[-0.85, 0.63, 0]}>
            <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell064_7" position={[-0.97, 0.9, -0.02]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell065_95" position={[-0.86, 0.87, 0.1]}>
            <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell066_96" position={[-0.91, 0.63, 0.12]}>
            <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell067_97" position={[-0.65, 0.87, 0.02]}>
            <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell068_98" position={[-0.15, 0.58, 0]}>
            <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell069_99" position={[-0.42, 0.58, 0.19]}>
            <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell070_100" position={[-0.11, 0.94, -0.08]}>
            <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell071_101" position={[-0.32, 0.88, 0.03]}>
            <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell072_102" position={[-0.46, 0.63, 0.02]}>
            <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell073_103" position={[-0.49, 0.9, 0.11]}>
            <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell074_104" position={[-0.21, 0.88, -0.04]}>
            <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell075_105" position={[-0.09, 0.86, -0.08]}>
            <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell076_106" position={[-0.37, 0.46, 0.92]}>
            <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell077_107" position={[-0.57, 0.14, 0.7]}>
            <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell078_108" position={[-0.38, 0.06, 0.94]}>
            <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell079_109" position={[-0.18, 0.06, 0.79]}>
            <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell080_110" position={[-0.15, 0.26, 0.87]}>
            <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell081_111" position={[-0.42, 0.23, 0.79]}>
            <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell082_112" position={[-0.8, 0.28, 0.77]}>
            <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell083_113" position={[-0.06, 0.43, 0.94]}>
            <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell084_8" position={[-0.16, 1.01, -0.05]}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell085_9" position={[-0.2, 1.01, 0.05]}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell086_114" position={[-0.07, 0.98, -0.08]}>
            <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell087_10" position={[-0.06, 0.96, -0.06]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell088_11" position={[-0.05, 0.99, -0.05]}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell089_12" position={[-0.1, 1, -0.07]}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell090_13" position={[-0.13, 1, -0.01]}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell091_115" position={[-0.65, 0.38, 0.17]}>
            <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell092_116" position={[-0.8, 0.13, 0.07]}>
            <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell093_117" position={[-0.65, 0.1, 0.28]}>
            <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell094_118" position={[-0.58, 0.29, 0.26]}>
            <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell095_14" position={[-0.53, 0.25, -0.09]}>
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell096_119" position={[-0.91, 0.4, 0.09]}>
            <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell097_120" position={[-0.87, 0.23, 0.34]}>
            <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell098_121" position={[-0.59, 0.25, -0.02]}>
            <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell099_122" position={[-0.11, 1.59, 0.21]}>
            <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell100_123" position={[-0.12, 1.84, 0.01]}>
            <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell101_124" position={[-0.14, 1.59, 0.03]}>
            <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell102_15" position={[-0.01, 1.57, 0.03]}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell103_125" position={[-0.43, 1.91, 0.15]}>
            <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell104_126" position={[-0.33, 1.71, 0.39]}>
            <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell105_127" position={[-0.37, 1.67, 0.12]}>
            <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell106_128" position={[-0.12, 1.76, 0.15]}>
            <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell107_129" position={[-0.77, 1.06, 0.09]}>
            <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell108_130" position={[-0.79, 1.17, 0.08]}>
            <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell109_131" position={[-0.67, 1.07, 0.81]}>
            <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell110_132" position={[-0.66, 1.15, 0.5]}>
            <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell111_133" position={[-0.88, 1.05, -0.08]}>
            <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell112_134" position={[-0.55, 1.08, 0.78]}>
            <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell113_135" position={[-0.59, 1.17, 0.06]}>
            <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell114_136" position={[-0.78, 1.82, 0.27]}>
            <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell115_137" position={[-0.62, 1.41, 0.11]}>
            <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell116_138" position={[-0.57, 1.52, 0.36]}>
            <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell117_16" position={[-0.53, 1.5, -0.04]}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell118_139" position={[-0.81, 1.89, 0.02]}>
            <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell119_140" position={[-0.82, 1.42, 0.38]}>
            <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell120_141" position={[-0.86, 1.51, 0.1]}>
            <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell121_142" position={[-0.58, 1.63, 0.06]}>
            <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell122_143" position={[-0.25, 1.44, 0.38]}>
            <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell123_144" position={[-0.11, 1.3, 0.65]}>
            <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell124_145" position={[-0.33, 1.17, 0.09]}>
            <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell125_146" position={[-0.16, 1.34, 0.18]}>
            <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell126_147" position={[-0.35, 1.23, 0.49]}>
            <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell127_148" position={[-0.29, 1.11, 0.85]}>
            <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell128_149" position={[-0.27, 1.42, 0.62]}>
            <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell129_17" position={[0, 1.46, 0.27]}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell130_150" position={[-0.14, 1.57, 0.94]}>
            <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell131_151" position={[-0.4, 1.6, 0.77]}>
            <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell132_152" position={[-0.58, 1.85, 0.67]}>
            <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell133_153" position={[-0.75, 1.1, 0.91]}>
            <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell134_154" position={[-0.91, 1.85, 0.65]}>
            <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell135_155" position={[-0.38, 1.27, 0.9]}>
            <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell136_156" position={[-0.7, 1.38, 0.8]}>
            <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell137_157" position={[-0.25, 1.86, 0.88]}>
            <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell138_158" position={[-0.08, 1.6, 0.78]}>
            <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell139_159" position={[-0.04, 1.59, 0.45]}>
            <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell140_18" position={[-0.05, 1.45, 0.88]}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell141_160" position={[-0.04, 1.88, 0.91]}>
            <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell142_161" position={[-0.11, 1.91, 0.85]}>
            <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell143_162" position={[-0.05, 1.83, 0.63]}>
            <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell144_19" position={[0, 1.83, 0.25]}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell145_20" position={[-0.07, 1.99, 0.94]}>
            <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell146_21" position={[-0.9, 1.22, 0.02]}>
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell147_163" position={[-0.9, 1.17, 0.56]}>
            <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell148_164" position={[-0.94, 1.11, 0.11]}>
            <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell149_22" position={[-1, 1.09, -0.06]}>
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell150_23" position={[-0.97, 1.22, -0.05]}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell151_165" position={[-0.93, 1.24, 0.16]}>
            <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell152_24" position={[-0.99, 1.27, -0.06]}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell153_166" position={[-0.21, 1.91, 0.59]}>
            <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell154_167" position={[-0.18, 1.66, 0.51]}>
            <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell155_168" position={[-0.08, 1.76, 0.27]}>
            <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell156_169" position={[-0.07, 1.93, 0.2]}>
            <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell157_170" position={[-0.18, 1.81, 0.63]}>
            <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell158_25" position={[0, 1.9, 0.05]}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell159_26" position={[0, 1.96, 0.02]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell160_27" position={[-0.96, 0.99, -0.41]}>
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell161_28" position={[-0.9, 0.97, -0.23]}>
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell162_171" position={[-0.66, 0.98, -0.22]}>
            <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell163_29" position={[-0.95, 0.95, -0.44]}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell164_172" position={[-0.62, 0.97, -0.41]}>
            <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell165_30" position={[-0.64, 0.93, -0.48]}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell166_173" position={[-0.81, 0.97, -0.41]}>
            <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell167_174" position={[-0.24, 0.37, -0.89]}>
            <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell168_175" position={[-0.47, 0.14, -0.77]}>
            <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell169_176" position={[-0.25, 0.16, -0.84]}>
            <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell170_177" position={[-0.16, 0.36, -0.64]}>
            <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell171_178" position={[-0.73, 0.04, -0.95]}>
            <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell172_179" position={[-0.39, 0.41, -0.68]}>
            <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell173_180" position={[-0.67, 0.19, -0.9]}>
            <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell174_181" position={[-0.56, 0.36, -0.77]}>
            <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell175_182" position={[-0.24, 0.42, -0.32]}>
            <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell176_183" position={[-0.39, 0.37, -0.48]}>
            <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell177_184" position={[-0.43, 0.19, -0.25]}>
            <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell178_185" position={[-0.2, 0.17, -0.46]}>
            <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell179_186" position={[-0.44, 0.13, -0.46]}>
            <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell180_187" position={[-0.53, 0.41, -0.38]}>
            <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell181_188" position={[-0.18, 0.14, -0.21]}>
            <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell182_189" position={[-0.14, 0.67, -0.88]}>
            <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell183_190" position={[-0.41, 0.85, -0.76]}>
            <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell184_191" position={[-0.12, 0.85, -0.77]}>
            <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell185_192" position={[-0.25, 0.65, -0.67]}>
            <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell186_193" position={[-0.21, 0.88, -0.8]}>
            <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell187_194" position={[-0.39, 0.66, -0.83]}>
            <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell188_195" position={[-0.25, 0.88, -0.62]}>
            <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell189_196" position={[-0.21, 0.67, -0.52]}>
            <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell190_197" position={[-0.19, 0.89, -0.35]}>
            <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell191_198" position={[-0.2, 0.58, -0.29]}>
            <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell192_199" position={[-0.44, 0.61, -0.47]}>
            <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell193_200" position={[-0.45, 0.9, -0.47]}>
            <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell194_201" position={[-0.47, 0.96, -0.21]}>
            <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell195_202" position={[-0.42, 0.71, -0.22]}>
            <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell196_31" position={[-0.53, 0.99, -0.15]}>
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell197_203" position={[-0.62, 0.63, -0.48]}>
            <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell198_204" position={[-0.77, 0.54, -0.21]}>
            <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell199_205" position={[-0.64, 0.53, -0.44]}>
            <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell200_206" position={[-0.88, 0.79, -0.2]}>
            <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell201_207" position={[-0.68, 0.76, -0.24]}>
            <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell202_208" position={[-0.84, 0.8, -0.42]}>
            <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell203_209" position={[-0.89, 0.58, -0.41]}>
            <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell204_210" position={[-0.66, 0.89, -0.31]}>
            <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell205_211" position={[-0.73, 0.6, -0.77]}>
            <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell206_32" position={[-0.57, 1.01, -0.56]}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell207_212" position={[-0.92, 0.8, -0.71]}>
            <mesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell208_213" position={[-0.8, 0.89, -0.74]}>
            <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell209_214" position={[-0.61, 0.9, -0.77]}>
            <mesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell210_215" position={[-0.6, 0.9, -0.6]}>
            <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell211_216" position={[-0.86, 0.43, -0.89]}>
            <mesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell212_217" position={[-0.92, 0.21, -0.8]}>
            <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell213_218" position={[-0.64, 0.22, -0.21]}>
            <mesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell214_219" position={[-0.74, 0.11, -0.56]}>
            <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell215_220" position={[-0.8, 0.31, -0.55]}>
            <mesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell216_221" position={[-0.92, 0.11, -0.73]}>
            <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell217_222" position={[-0.9, 0.27, -0.34]}>
            <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell218_223" position={[-0.92, 0.12, -0.31]}>
            <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell219_33" position={[-0.96, 0.03, -0.99]}>
            <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell220_34" position={[-0.31, 1.02, -0.21]}>
            <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell221_224" position={[-0.7, 1.03, -0.16]}>
            <mesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell222_35" position={[-0.17, 0.99, -0.17]}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell223_225" position={[-0.55, 1.03, -0.45]}>
            <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell224_36" position={[-0.41, 1.03, -0.38]}>
            <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell225_226" position={[-0.67, 1.08, -0.34]}>
            <mesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell226_227" position={[-0.57, 1.1, -0.43]}>
            <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell227_228" position={[-0.56, 1.07, -0.23]}>
            <mesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell228_229" position={[-0.8, 1.13, -0.85]}>
            <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell229_230" position={[-0.67, 1.31, -0.63]}>
            <mesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell230_231" position={[-0.89, 1.1, -0.58]}>
            <mesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell231_232" position={[-0.66, 1.39, -0.89]}>
            <mesh name="Object_466" geometry={nodes.Object_466.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell232_233" position={[-0.87, 1.32, -0.65]}>
            <mesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell233_234" position={[-0.92, 1.29, -0.76]}>
            <mesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell234_235" position={[-0.71, 1.14, -0.61]}>
            <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell235_236" position={[-0.89, 1.27, -0.88]}>
            <mesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell236_237" position={[-0.66, 1.83, -0.9]}>
            <mesh name="Object_476" geometry={nodes.Object_476.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell237_238" position={[-0.65, 1.64, -0.65]}>
            <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell238_239" position={[-0.68, 1.83, -0.64]}>
            <mesh name="Object_480" geometry={nodes.Object_480.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell239_240" position={[-0.89, 1.88, -0.6]}>
            <mesh name="Object_482" geometry={nodes.Object_482.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell240_241" position={[-0.84, 1.66, -0.88]}>
            <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell241_242" position={[-0.89, 1.88, -0.81]}>
            <mesh name="Object_486" geometry={nodes.Object_486.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell242_243" position={[-0.89, 1.66, -0.67]}>
            <mesh name="Object_488" geometry={nodes.Object_488.geometry} material={materials['Material.001']} />
          </group>
          <group name="Cube_cell013_cell243_244" position={[-0.61, 1.59, -0.9]}>
            <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials['Material.001']} />
          </group>
          <group name="Plane001_245" position={[-0.21, -2, -0.03]} />
          <group name="Plane_1" position={[0.19, -0.02, 0]} scale={1.93} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Surprise.glb')
