/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import url from "../objects/Cannon.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.49}>
        <mesh geometry={nodes.defaultMaterial013.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial018.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial008.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial011.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial010.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial016.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial015.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial014.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial017.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial019.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial007.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial009.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial012.geometry} material={materials.material_0} />
        <mesh geometry={nodes.defaultMaterial020.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cannon.glb')
